### ISSUE TITLE
Create T-Groundair System Model

### ISSUE THREAD

**Issue by rsanz** [Ingenia-SE/T-Groundair#1]
Create the **SysML model** to support the development of the system. Note that this model will not be the only model in the project. The folder "models" shall contain all models (SysML, V-REP, Simulink, etc).

**Comment by rsanz** [comment]
V-REP -> Gazebo

**Comment by alvarob9** [comment]
The SysML Model has progressed during the last months, sorry for not having presented the results here. General structure, as well as a first version from server and UAV can be found in model_development branch. UGV's first version is almost finished. Changes will be made while software integration progresses.

**Comment by rsanz** [comment]
When a first release to move to master?

**Comment by alvarob9** [comment]
I am waiting for some diagrams from UGV team. My intention was moving that first release to master branch as soon as I receive them (hope that shortly) and we integrate that, to have a full first overview. However, if you think that it would be better to have that unfinished version placed in master branch, please tell me and I'll begin the pull request.

**Comment by alvarob9** [comment]
SysML first release moved to master branch. For the moment, the view was based on our initial intention of implementing the system physically. Is that ok?

**Comment by rsanz** [comment]
OK. Good. Don't focus on the SysML model now. It is quite late and we shall focus on development and integration even if chaotic without a model. We will get back to this at the end (if there's time).
I close this issue.
